name: online-shopping-prediction
channels:
  - defaults  
  - conda-forge  
dependencies:
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - ucimlrepo
  - ipykernel
  - vegafusion==1.6.9
  - altair
  - pip:
    - altair_ally>=0.1.1
