name: online-shopping-prediction
channels:
  - conda-forge  
  - defaults  
dependencies:
  - python=3.11
  - altair==5.4.1
  - ipykernel==6.29.5
  - matplotlib==3.9.2
  - numpy==2.1.3
  - pandas==2.2.3
  - pandera=0.20.4
  - scikit-learn==1.5.2
  - scipy==1.14.1
  - ucimlrepo==0.0.7
  - vegafusion==1.6.9
  - vl-convert-python[version'>=1.6.0']
  - nb_conda_kernels==2.5.1
  - quarto=1.5.57
  - click=8.1.7
  - tabulate=0.9.0
  - make=4.4.1
  - pytest=8.3.4
  - pip:
    - altair_ally>=0.1.1
    - deepchecks==0.18.1