name: online-shopping-prediction
channels:
  - conda-forge  
  - defaults  
dependencies:
  - python>=3.11,<3.13
  - altair
  - ipykernel
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - ucimlrepo
  - vegafusion==1.6.9
  - vl-convert-python[version'>=1.6.0']
  - pip:
    - altair_ally>=0.1.1